Library JclStackTraceViewerExpertDLL;
{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclStackTraceViewerExpertDLL-L.xml)

     Last generated: 11-04-2009  11:49:00 UTC
-----------------------------------------------------------------------------
}

{$R *.res}
{$ALIGN 8}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS OFF}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION ON}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO OFF}
{$SAFEDIVIDE OFF}
{$STACKFRAMES OFF}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST ON}
{$MINENUMSIZE 1}
{$IMAGEBASE $58120000}
{$DESCRIPTION 'JCL Stack Trace Viewer'}
{$LIBSUFFIX '110'}
{$IMPLICITBUILD OFF}

{$DEFINE BCB}
{$DEFINE RELEASE}

uses
  ToolsAPI,
  StackTraceViewerImpl in '..\..\experts\stackviewer\StackTraceViewerImpl.pas' ,
  ExceptInfoFrame in '..\..\experts\stackviewer\ExceptInfoFrame.pas' {frmException: TFrame},
  StackFrame in '..\..\experts\stackviewer\StackFrame.pas' {frmStack: TFrame},
  ThreadFrame in '..\..\experts\stackviewer\ThreadFrame.pas' {frmThread: TFrame},
  StackFrame2 in '..\..\experts\stackviewer\StackFrame2.pas' {frmStack2: TFrame},
  ModuleFrame in '..\..\experts\stackviewer\ModuleFrame.pas' {frmModule: TFrame},
  StackViewForm in '..\..\experts\stackviewer\StackViewForm.pas' {frmStackView},
  StackTraceViewerConfigFrame in '..\..\experts\stackviewer\StackTraceViewerConfigFrame.pas' {JclStackTraceViewerConfigFrame: TFrame},
  JclDebugStackUtils in '..\..\experts\stackviewer\JclDebugStackUtils.pas' ,
  StackViewUnit in '..\..\experts\stackviewer\StackViewUnit.pas' ,
  StackCodeUtils in '..\..\experts\stackviewer\StackCodeUtils.pas' ,
  ExceptionViewerOptionsUnit in '..\..\experts\stackviewer\ExceptionViewerOptionsUnit.pas' ,
  StackLineNumberTranslator in '..\..\experts\stackviewer\StackLineNumberTranslator.pas' ,
  JclStackTraceViewerAPI in '..\..\experts\stackviewer\JclStackTraceViewerAPI.pas' ,
  FileSearcherUnit in '..\..\experts\stackviewer\FileSearcherUnit.pas' 
  ;

exports
  JCLWizardInit name WizardEntryPoint;

end.
