Library JclThreadNameExpertDLLD50;
{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclThreadNameExpertDLL-L.xml)

     Last generated: 26-12-2005  12:57:54 UTC
-----------------------------------------------------------------------------
}

{$R *.res}
{$ALIGN ON}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS OFF}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION ON}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO OFF}
{$SAFEDIVIDE OFF}
{$STACKFRAMES OFF}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST OFF}
{$MINENUMSIZE 1}
{$IMAGEBASE $58050000}
{$DESCRIPTION 'JCL Thread Name IDE expert'}
{$IMPLICITBUILD OFF}

uses
  ToolsAPI,
  ThreadExpertSharedNames in '..\..\experts\debug\threadnames\ThreadExpertSharedNames.pas' ,
  ThreadExpertUnit in '..\..\experts\debug\threadnames\ThreadExpertUnit.pas' 
  ;

exports
  JCLWizardInit name WizardEntryPoint;

end.
