//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpert-D.xml)
            
     Last generated: 21-05-2006  13:04:22 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\debug\dialog\JclOtaExcDlgWizard.pas", Jclotaexcdlgwizard, JclOtaExcDlgForm); 
USEFORMNS("..\..\experts\debug\dialog\JclOtaExcDlgFileFrame.pas", Jclotaexcdlgfileframe, JclOtaExcDlgFilePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\debug\dialog\JclOtaExcDlgFormFrame.pas", Jclotaexcdlgformframe, JclOtaExcDlgFormPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\debug\dialog\JclOtaExcDlgSystemFrame.pas", Jclotaexcdlgsystemframe, JclOtaExcDlgSystemPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\debug\dialog\JclOtaExcDlgTraceFrame.pas", Jclotaexcdlgtraceframe, JclOtaExcDlgTracePage); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

