//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpertDLL-L.xml)
            
     Last generated: 26-01-2008  11:13:10 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\repository\JclOtaExcDlgWizard.pas", Jclotaexcdlgwizard, JclOtaExcDlgForm); 
USEFORMNS("..\..\experts\repository\JclOtaExcDlgFileFrame.pas", Jclotaexcdlgfileframe, JclOtaExcDlgFilePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgFormFrame.pas", Jclotaexcdlgformframe, JclOtaExcDlgFormPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgSystemFrame.pas", Jclotaexcdlgsystemframe, JclOtaExcDlgSystemPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgTraceFrame.pas", Jclotaexcdlgtraceframe, JclOtaExcDlgTracePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgIgnoreFrame.pas", Jclotaexcdlgignoreframe, JclOtaExcDlgIgnorePage); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Library source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

