//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpert-D.xml)
            
     Last generated: 23-07-2009  12:59:40 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\repository\JclOtaExcDlgWizard.pas", Jclotaexcdlgwizard, JclOtaExcDlgForm); 
USEFORMNS("..\..\experts\repository\JclOtaExcDlgFileFrame.pas", Jclotaexcdlgfileframe, JclOtaExcDlgFilePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgFormFrame.pas", Jclotaexcdlgformframe, JclOtaExcDlgFormPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgSystemFrame.pas", Jclotaexcdlgsystemframe, JclOtaExcDlgSystemPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgLogFrame.pas", Jclotaexcdlglogframe, JclOtaExcDlgLogPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgTraceFrame.pas", Jclotaexcdlgtraceframe, JclOtaExcDlgTracePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgThreadFrame.pas", Jclotaexcdlgthreadframe, JclOtaExcDlgThreadPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\JclOtaExcDlgIgnoreFrame.pas", Jclotaexcdlgignoreframe, JclOtaExcDlgIgnoredPage); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

