//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpert-D.xml)
            
     Last generated: 16-02-2007  19:07:51 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclRepositoryExpertC50.res");
USEUNIT("..\..\experts\debug\dialog\JclOtaRepositoryUtils.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgRepository.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaRepositoryReg.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgWizard.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgFileFrame.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgFormFrame.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgSystemFrame.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgTraceFrame.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaTemplates.pas");
USEUNIT("..\..\experts\debug\dialog\JclOtaExcDlgIgnoreFrame.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("JclBaseExpertC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
