//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclSIMDViewExpert-D.xml)
            
     Last generated: 26-12-2005  11:30:52 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclSIMDViewExpertC50.res");
USEUNIT("..\..\experts\debug\simdview\JclSIMDViewForm.pas");
USEUNIT("..\..\experts\debug\simdview\JclSIMDView.pas");
USEUNIT("..\..\experts\debug\simdview\JclSIMDUtils.pas");
USEUNIT("..\..\experts\debug\simdview\JclSIMDModifyForm.pas");
USEUNIT("..\..\experts\debug\simdview\JclSIMDCpuInfo.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("JclBaseExpertC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
