//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (%XMLNAME%)
            
     Last generated: %DATETIME%     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("%NAME%.res");
<%%% START FILES %%%>
USEUNIT("%FILENAME%");
<%%% END FILES %%%>
<%%% START REQUIRES %%%>
USEPACKAGE("%NAME%.bpi");
<%%% END REQUIRES %%%>
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
<%%% BEGIN PACKAGEONLY %%%>
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
<%%% END PACKAGEONLY %%%>
<%%% BEGIN RUNONLY %%%>
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
<%%% END RUNONLY %%%>
<%%% BEGIN DESIGNONLY %%%>
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
<%%% END DESIGNONLY %%%>
<%%% BEGIN LIBRARYONLY %%%>
//   Library source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
<%%% END LIBRARYONLY %%%>
<%%% BEGIN PROGRAMONLY %%%>
//   Program source.
//---------------------------------------------------------------------------
#pragma argsused
WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
        return 0;
}
<%%% END PROGRAMONLY %%%>
//---------------------------------------------------------------------------
