//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclBaseExpert-D.xml)
            
     Last generated: 08-01-2006  17:11:05 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclBaseExpertC50.res");
USEUNIT("..\..\experts\common\JclOtaUtils.pas");
USEUNIT("..\..\experts\common\JclOtaResources.pas");
USEUNIT("..\..\experts\common\JclOtaConsts.pas");
USEUNIT("..\..\experts\common\JclOtaExceptionForm.pas");
USEUNIT("..\..\experts\common\JclOtaConfigurationForm.pas");
USEUNIT("..\..\experts\common\JclOtaActionConfigureSheet.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
