//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (Jcl-R.xml)
            
     Last generated: 26-12-2005  11:30:52 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclC50.res");
USEUNIT("..\..\source\common\Jcl8087.pas");
USEUNIT("..\..\source\common\JclAbstractContainers.pas");
USEUNIT("..\..\source\common\JclAlgorithms.pas");
USEUNIT("..\..\source\common\JclArrayLists.pas");
USEUNIT("..\..\source\common\JclArraySets.pas");
USEUNIT("..\..\source\common\JclBase.pas");
USEUNIT("..\..\source\common\JclBinaryTrees.pas");
USEUNIT("..\..\source\common\JclBorlandTools.pas");
USEUNIT("..\..\source\common\JclComplex.pas");
USEUNIT("..\..\source\common\JclCompression.pas");
USEUNIT("..\..\source\common\JclContainerIntf.pas");
USEUNIT("..\..\source\common\JclCounter.pas");
USEUNIT("..\..\source\common\JclDateTime.pas");
USEUNIT("..\..\source\common\JclEDI.pas");
USEUNIT("..\..\source\common\JclEDISEF.pas");
USEUNIT("..\..\source\common\JclEDITranslators.pas");
USEUNIT("..\..\source\common\JclEDIXML.pas");
USEUNIT("..\..\source\common\JclEDI_ANSIX12.pas");
USEUNIT("..\..\source\common\JclEDI_ANSIX12_Ext.pas");
USEUNIT("..\..\source\common\JclEDI_UNEDIFACT.pas");
USEUNIT("..\..\source\common\JclEDI_UNEDIFACT_Ext.pas");
USEUNIT("..\..\source\common\JclExprEval.pas");
USEUNIT("..\..\source\common\JclFileUtils.pas");
USEUNIT("..\..\source\common\JclHashMaps.pas");
USEUNIT("..\..\source\common\JclHashSets.pas");
USEUNIT("..\..\source\common\JclIniFiles.pas");
USEUNIT("..\..\source\common\JclLinkedLists.pas");
USEUNIT("..\..\source\common\JclLogic.pas");
USEUNIT("..\..\source\common\JclMath.pas");
USEUNIT("..\..\source\common\JclMIDI.pas");
USEUNIT("..\..\source\common\JclMime.pas");
USEUNIT("..\..\source\common\JclPCRE.pas");
USEUNIT("..\..\source\common\JclQueues.pas");
USEUNIT("..\..\source\common\JclResources.pas");
USEUNIT("..\..\source\common\JclRTTI.pas");
USEUNIT("..\..\source\common\JclSchedule.pas");
USEUNIT("..\..\source\common\JclStacks.pas");
USEUNIT("..\..\source\common\JclStatistics.pas");
USEUNIT("..\..\source\common\JclStrHashMap.pas");
USEUNIT("..\..\source\common\JclStrings.pas");
USEUNIT("..\..\source\common\JclSysInfo.pas");
USEUNIT("..\..\source\common\JclSysUtils.pas");
USEUNIT("..\..\source\common\JclUnitConv.pas");
USEUNIT("..\..\source\common\JclUnitVersioning.pas");
USEUNIT("..\..\source\common\JclUnitVersioningProviders.pas");
USEUNIT("..\..\source\common\JclValidation.pas");
USEUNIT("..\..\source\common\JclVectors.pas");
USEUNIT("..\..\source\common\JclWideStrings.pas");
USEUNIT("..\..\source\common\pcre.pas");
USEUNIT("..\..\source\windows\Hardlinks.pas");
USEUNIT("..\..\source\windows\JclAppInst.pas");
USEUNIT("..\..\source\windows\JclCIL.pas");
USEUNIT("..\..\source\windows\JclCLR.pas");
USEUNIT("..\..\source\windows\JclCOM.pas");
USEUNIT("..\..\source\windows\JclConsole.pas");
USEUNIT("..\..\source\windows\JclDebug.pas");
USEUNIT("..\..\source\windows\JclHookExcept.pas");
USEUNIT("..\..\source\windows\JclLANMan.pas");
USEUNIT("..\..\source\windows\JclLocales.pas");
USEUNIT("..\..\source\windows\JclMapi.pas");
USEUNIT("..\..\source\windows\JclMetadata.pas");
USEUNIT("..\..\source\windows\JclMiscel.pas");
USEUNIT("..\..\source\windows\JclMsdosSys.pas");
USEUNIT("..\..\source\windows\JclMultimedia.pas");
USEUNIT("..\..\source\windows\JclNTFS.pas");
USEUNIT("..\..\source\windows\JclPeImage.pas");
USEUNIT("..\..\source\windows\JclRegistry.pas");
USEUNIT("..\..\source\windows\JclSecurity.pas");
USEUNIT("..\..\source\windows\JclShell.pas");
USEUNIT("..\..\source\windows\JclStructStorage.pas");
USEUNIT("..\..\source\windows\JclSvcCtrl.pas");
USEUNIT("..\..\source\windows\JclSynch.pas");
USEUNIT("..\..\source\windows\JclTask.pas");
USEUNIT("..\..\source\windows\JclTD32.pas");
USEUNIT("..\..\source\windows\JclUnicode.pas");
USEUNIT("..\..\source\windows\JclWin32.pas");
USEUNIT("..\..\source\windows\JclWinMIDI.pas");
USEUNIT("..\..\source\windows\MSTask.pas");
USEUNIT("..\..\source\windows\Snmp.pas");
USEUNIT("..\..\source\windows\zlibh.pas");
USEUNIT("..\..\source\vcl\JclGraphics.pas");
USEUNIT("..\..\source\vcl\JclGraphUtils.pas");
USEUNIT("..\..\source\vcl\JclPrint.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vcljpg50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
