//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclContainers-R.xml)
            
     Last generated: 16-01-2008  21:18:34 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclContainersC50.res");
USEUNIT("..\..\source\common\JclAbstractContainers.pas");
USEUNIT("..\..\source\common\JclAlgorithms.pas");
USEUNIT("..\..\source\common\JclArrayLists.pas");
USEUNIT("..\..\source\common\JclArraySets.pas");
USEUNIT("..\..\source\common\JclBinaryTrees.pas");
USEUNIT("..\..\source\common\JclContainerIntf.pas");
USEUNIT("..\..\source\common\JclHashMaps.pas");
USEUNIT("..\..\source\common\JclHashSets.pas");
USEUNIT("..\..\source\common\JclLinkedLists.pas");
USEUNIT("..\..\source\common\JclQueues.pas");
USEUNIT("..\..\source\common\JclSortedMaps.pas");
USEUNIT("..\..\source\common\JclStacks.pas");
USEUNIT("..\..\source\common\JclTrees.pas");
USEUNIT("..\..\source\common\JclVectors.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("JclC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
