//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpertDLL-L.xml)
            
     Last generated: 23-07-2009  11:30:30 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclRepositoryExpertDLLC50.res");
USEUNIT("..\..\experts\repository\JclOtaTemplates.pas");
USEUNIT("..\..\experts\repository\JclOtaRepositoryUtils.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgRepository.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgWizard.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgFileFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgFormFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgSystemFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgLogFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgTraceFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaExcDlgIgnoreFrame.pas");
USEUNIT("..\..\experts\repository\JclOtaRepositoryReg.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("JclBaseExpertC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Library source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
