//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclStackTraceViewerExpertDLL-L.xml)
            
     Last generated: 24-07-2009  09:49:30 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclStackTraceViewerExpertDLLC50.res");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerImpl.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerExceptInfoFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerStackFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerThreadFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerModuleFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerMainFormDelphi.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerMainFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerConfigFrame.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerClasses.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerStackCodeUtils.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerOptions.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerAPIImpl.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerAPI.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclStackTraceViewerStackUtils.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclDebugSerialization.pas");
USEUNIT("..\..\experts\stacktraceviewer\JclDebugXMLDeserializer.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("JclBaseExpertC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Library source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
