//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclVcl-R.xml)
            
     Last generated: 15-09-2008  22:32:02 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclVclC50.res");
USEUNIT("..\..\source\vcl\JclPrint.pas");
USEUNIT("..\..\source\vcl\JclGraphUtils.pas");
USEUNIT("..\..\source\vcl\JclGraphics.pas");
USEUNIT("..\..\source\vcl\JclFont.pas");
USEUNIT("..\..\source\vcl\JclVersionControl.pas");
USEUNIT("..\..\source\vcl\JclVersionCtrlCVSImpl.pas");
USEUNIT("..\..\source\vcl\JclVersionCtrlSVNImpl.pas");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("vcljpg50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
