//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclVersionControlExpertDLL-L.xml)
            
     Last generated: 08-01-2006  17:55:07 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclVersionControlExpertDLLC50.res");
USEUNIT("..\..\experts\versioncontrol\VersionControlImpl.pas");
USEUNIT("..\..\experts\versioncontrol\JclVersionCtrlCommonOptions.pas");
USEUNIT("..\..\experts\versioncontrol\JclVersionCtrlCVSImpl.pas");
USEUNIT("..\..\experts\versioncontrol\JclVersionCtrlSVNImpl.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");
USEPACKAGE("JclBaseExpertC50.bpi");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Library source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
