//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JediApi-R.xml)
            
     Last generated: 16-08-2008  14:35:48 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JediApiC50.res");
USEUNIT("..\..\source\apilib\JwaWindows.pas");
USEUNIT("..\..\source\apilib\JwaVista.pas");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
