program BuildTest;

uses
  Jcl8087 in '..\..\source\Jcl8087.pas',
  JclAppInst in '..\..\source\JclAppInst.pas',
  JclBase in '..\..\source\JclBase.pas',
  JclCIL in '..\..\source\JclCIL.pas',
  JclClr in '..\..\source\JclCLR.pas',
  JclCOM in '..\..\source\JclCOM.pas',
  JclComplex in '..\..\source\JclComplex.pas',
  JclConsole in '..\..\source\JclConsole.pas',
  JclCounter in '..\..\source\JclCounter.pas',
  JclDateTime in '..\..\source\JclDateTime.pas',
  JclDebug in '..\..\source\JclDebug.pas',
  // JclDotNet in '..\..\source\JclDotNet.pas',
  JclEDI in '..\..\source\JclEDI.pas',
  JclEDIXML in '..\..\source\JclEDIXML.pas',
  JclExprEval in '..\..\source\JclExprEval.pas',
  JclFileUtils in '..\..\source\JclFileUtils.pas',
  JclGraphics in '..\..\source\JclGraphics.pas',
  JclGraphUtils in '..\..\source\JclGraphUtils.pas',
  JclHookExcept in '..\..\source\JclHookExcept.pas',
  JclIniFiles in '..\..\source\JclIniFiles.pas',
  JclLANMan in '..\..\source\JclLANMan.pas',
  JclLocales in '..\..\source\JclLocales.pas',
  JclLogic in '..\..\source\JclLogic.pas',
  JclMapi in '..\..\source\JclMapi.pas',
  JclMath in '..\..\source\JclMath.pas',
  JclMetadata in '..\..\source\JclMetadata.pas',
  JclMIDI in '..\..\source\JclMIDI.pas',
  JclMime in '..\..\source\JclMime.pas',
  JclMiscel in '..\..\source\JclMiscel.pas',
  JclMultimedia in '..\..\source\JclMultimedia.pas',
  JclNTFS in '..\..\source\JclNTFS.pas',
  JclPeImage in '..\..\source\JclPeImage.pas',
  JclPrint in '..\..\source\JclPrint.pas',
  JclRegistry in '..\..\source\JclRegistry.pas',
  JclResources in '..\..\source\JclResources.pas',
  JclRTTI in '..\..\source\JclRTTI.pas',
  JclSecurity in '..\..\source\JclSecurity.pas',
  JclShell in '..\..\source\JclShell.pas',
  JclSchedule in '..\..\source\JclSchedule.pas',
  JclStatistics in '..\..\source\JclStatistics.pas',
  JclStrHashMap in '..\..\source\JclStrHashMap.pas',
  JclStrings in '..\..\source\JclStrings.pas',
  JclSvcCtrl in '..\..\source\JclSvcCtrl.pas',
  JclSynch in '..\..\source\JclSynch.pas',
  JclSysInfo in '..\..\source\JclSysInfo.pas',
  JclSysUtils in '..\..\source\JclSysUtils.pas',
  // JclTask in '..\..\source\JclTask.pas',
  JclTD32 in '..\..\source\JclTD32.pas',
  JclUnicode in '..\..\source\JclUnicode.pas',
  JclUnitConv in '..\..\source\JclUnitConv.pas',
  JclWin32 in '..\..\source\JclWin32.pas',
  JclWinMidi in '..\..\source\JclWinMIDI.pas',
  LM in '..\..\source\LM.pas',
  Snmp in '..\..\source\Snmp.pas';

begin
end.
