//---------------------------------------------------------------------------

//#pragma hdrstop

#ifdef TEST_COMMON
#include "../../source/common/bzip2.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/Hardlinks.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/Jcl8087.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclAbstractContainers.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclAlgorithms.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclAnsiStrings.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclAppInst.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclArrayLists.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclArraySets.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclBase.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclBinaryTrees.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclBorlandTools.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclCIL.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclCLR.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclCOM.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclComplex.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclCompression.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclConsole.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclContainerIntf.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclCounter.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclDateTime.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclDebug.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclDotNet.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclEDI.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDI_ANSIX12.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDI_ANSIX12_Ext.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDI_UNEDIFACT.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDI_UNEDIFACT_Ext.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDISEF.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDITranslators.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclEDIXML.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclExprEval.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclFileUtils.hpp"
#endif TEST_COMMON
#ifdef TEST_VCL
#include "../../source/vcl/JclFont.hpp"
#endif TEST_VCL
#ifdef TEST_VCL
#include "../../source/vcl/JclGraphics.hpp"
#endif TEST_VCL
#ifdef TEST_VCL
#include "../../source/vcl/JclGraphUtils.hpp"
#endif TEST_VCL
#ifdef TEST_COMMON
#include "../../source/common/JclHashMaps.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclHashSets.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclHookExcept.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclIniFiles.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclLANMan.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclLinkedLists.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclLocales.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclLogic.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclMapi.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclMath.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclMetadata.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclMIDI.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclMime.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclMiscel.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclMsdosSys.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclMultimedia.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclNTFS.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclPCRE.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclPeImage.hpp"
#endif TEST_WINDOWS
#ifdef TEST_VCL
#include "../../source/vcl/JclPrint.hpp"
#endif TEST_VCL
#ifdef TEST_VISCLX
#include "../../source/visclx/JclQGraphics.hpp"
#endif TEST_VISCLX
#ifdef TEST_VISCLX
#include "../../source/visclx/JclQGraphUtils.hpp"
#endif TEST_VISCLX
#ifdef TEST_COMMON
#include "../../source/common/JclQueues.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclRegistry.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclResources.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclRTTI.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclSchedule.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclSecurity.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclShell.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclSimpleXml.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStacks.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStatistics.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStreams.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStrHashMap.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStringLists.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclStrings.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclStructStorage.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclSvcCtrl.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclSynch.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclSysInfo.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclSysUtils.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclTask.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclTD32.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclUnicode.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclUnitConv.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclUnitVersioning.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclUnitVersioningProviders.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclValidation.hpp"
#endif TEST_COMMON
#ifdef TEST_COMMON
#include "../../source/common/JclVectors.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclWideFormat.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/JclWideStrings.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/JclWin32.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclWin32Ex.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/JclWinMIDI.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/mscoree_TLB.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/mscorlib_TLB.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/MSHelpServices_TLB.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/MSTask.hpp"
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include "../../source/common/pcre.hpp"
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include "../../source/windows/Snmp.hpp"
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include "../../source/windows/zlibh.hpp"
#endif TEST_WINDOWS
#ifdef TEST_UNIX
#include "../../source/unix/zlibh.hpp"
#endif TEST_UNIX

//---------------------------------------------------------------------------

#pragma argsused
int main(int argc, char* argv[])
{
        return 0;
}
//---------------------------------------------------------------------------
 