//---------------------------------------------------------------------------

//#pragma hdrstop

#ifdef TEST_WINDOWS
#include <zlibh.hpp>
#endif TEST_WINDOWS
#ifdef TEST_UNIX
#include <zlibh.hpp>
#endif TEST_UNIX
#ifdef TEST_WINDOWS
#include <Snmp.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <pcre.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <MSTask.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <MSHelpServices_TLB.hpp>
#endif TEST_WINDOWS
//#ifdef TEST_WINDOWS
//#include <mscorlib_TLB.hpp> known to fail
//#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <mscoree_TLB.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclWinMIDI.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclWin32Ex.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclWin32.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclWideStrings.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclWideFormat.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclVectors.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclValidation.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclUnitVersioningProviders.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclUnitVersioning.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclUnitConv.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclUnicode.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclTrees.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclTD32.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclTask.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclSysUtils.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclSysInfo.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclSynch.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclSvcCtrl.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclStructStorage.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclStrings.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclStringLists.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclStrHashMap.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclStreams.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclStatistics.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclStacks.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclSortedMaps.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclSimpleXml.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclShell.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclSecurity.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclSchedule.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclRTTI.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclResources.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclRegistry.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclQueues.hpp>
#endif TEST_COMMON
#ifdef TEST_VISCLX
#include <JclQGraphUtils.hpp>
#endif TEST_VISCLX
#ifdef TEST_VISCLX
#include <JclQGraphics.hpp>
#endif TEST_VISCLX
#ifdef TEST_VCL
#include <JclPrint.hpp>
#endif TEST_VCL
#ifdef TEST_WINDOWS
#include <JclPeImage.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclPCRE.hpp>
#endif TEST_COMMON
//#ifdef TEST_WINDOWS
//#include <JclNTFS.hpp> no declaration for IPropertyStorage
//#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclMultimedia.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclMsdosSys.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclMiscel.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclMime.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclMIDI.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclMetadata.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclMath.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclMapi.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclLogic.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclLocales.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclLinkedLists.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclLANMan.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclIniFiles.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclHookExcept.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclHashSets.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclHashMaps.hpp>
#endif TEST_COMMON
#ifdef TEST_VCL
#include <JclGraphUtils.hpp>
#endif TEST_VCL
#ifdef TEST_VCL
#include <JclGraphics.hpp>
#endif TEST_VCL
#ifdef TEST_VCL
#include <JclFont.hpp>
#endif TEST_VCL
#ifdef TEST_COMMON
#include <JclFileUtils.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclExprEval.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDIXML.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDITranslators.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDISEF.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDI_UNEDIFACT_Ext.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDI_UNEDIFACT.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDI_ANSIX12_Ext.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDI_ANSIX12.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclEDI.hpp>
#endif TEST_COMMON
//#ifdef TEST_WINDOWS
//#include <JclDotNet.hpp> mscorlib_TLB.hpp is known to fail
//#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclDebug.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclDateTime.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclCounter.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclContainerIntf.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclConsole.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclCompression.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclComplex.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclCOM.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclCLR.hpp>
#endif TEST_WINDOWS
#ifdef TEST_WINDOWS
#include <JclCIL.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclBorlandTools.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclBinaryTrees.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclBase.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclArraySets.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclArrayLists.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <JclAppInst.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <JclAnsiStrings.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclAlgorithms.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <JclAbstractContainers.hpp>
#endif TEST_COMMON
#ifdef TEST_COMMON
#include <Jcl8087.hpp>
#endif TEST_COMMON
#ifdef TEST_WINDOWS
#include <Hardlinks.hpp>
#endif TEST_WINDOWS
#ifdef TEST_COMMON
#include <bzip2.hpp>
#endif TEST_COMMON

//---------------------------------------------------------------------------

#pragma argsused
int main(int argc, char* argv[])
{
        return 0;
}
//---------------------------------------------------------------------------
 