//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (Jcl-R.xml)
            
     Last generated: 15-03-2005  18:50:01 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclSIMDViewC5.res");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("CJcl50.bpi");
USEUNIT("..\JclOtaUtils.pas");
USEFORMNS("JclSIMDViewForm.pas", Jclsimdviewform, JclSIMDViewFrm);
USERES("JclSIMDIcon.dcr");
USEFORMNS("JclSIMDModifyForm.pas", Jclsimdmodifyform, JclSIMDModifyFrm);
USEUNIT("JclSIMDUtils.pas");
USEUNIT("JclSIMDView.pas");
USEFORMNS("JclSIMDCpuInfo.pas", Jclsimdcpuinfo, JclFormCpuInfo);
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------



