
function isalnum(_para1:longint):longint;cdecl;external clib name 'isalnum';
function isalpha(_para1:longint):longint;cdecl;external clib name 'isalpha';
function iscntrl(_para1:longint):longint;cdecl;external clib name 'iscntrl';
function isdigit(_para1:longint):longint;cdecl;external clib name 'isdigit';
function islower(_para1:longint):longint;cdecl;external clib name 'islower';
function isgraph(_para1:longint):longint;cdecl;external clib name 'isgraph';
function isprint(_para1:longint):longint;cdecl;external clib name 'isprint';
function ispunct(_para1:longint):longint;cdecl;external clib name 'ispunct';
function isspace(_para1:longint):longint;cdecl;external clib name 'isspace';
function isupper(_para1:longint):longint;cdecl;external clib name 'isupper';
function isxdigit(_para1:longint):longint;cdecl;external clib name 'isxdigit';
function isblank(_para1: longint):longint; cdecl;external clib name 'isblank';
function tolower(__c:longint):longint;cdecl;external clib name 'tolower';
function toupper(__c:longint):longint;cdecl;external clib name 'toupper';
function isascii(__c:longint):longint;cdecl;external clib name 'isascii';
function toascii(__c:longint):longint;cdecl;external clib name 'toascii';
function _toupper(_para1:longint):longint;cdecl;external clib name '_toupper';
function _tolower(_para1:longint):longint;cdecl;external clib name '_tolower';


{ ---------------------------------------------------------------------
    Borland compatibility types
  ---------------------------------------------------------------------}

// Type
