
const

   LD_LINUX_SO = 'ld-linux.so.2';
   LD_SO = 'ld-linux.so.2';
   LIBANL_SO = 'libanl.so.1';
   LIBBROKENLOCALE_SO = 'libBrokenLocale.so.1';
   LIBCRYPT_SO = 'libcrypt.so.1';
   LIBC_SO = 'libc.so.6';
   LIBDB1_SO = 'libdb1.so.2';
   LIBDB2_SO = 'libdb2.so.3';
   LIBDL_SO = 'libdl.so.2';
   LIBM_SO = 'libm.so.6';
   LIBNOVERSION_SO = 'libNoVersion.so.1';
   LIBNSL_SO = 'libnsl.so.1';
   LIBNSS_COMPAT_SO = 'libnss_compat.so.2';
   LIBNSS_DNS6_SO = 'libnss_dns6.so.2';
   LIBNSS_DNS_SO = 'libnss_dns.so.2';
   LIBNSS_FILES_SO = 'libnss_files.so.2';
   LIBNSS_HESIOD_SO = 'libnss_hesiod.so.2';
   LIBNSS_LDAP_SO = 'libnss_ldap.so.2';
   LIBNSS_NISPLUS_SO = 'libnss_nisplus.so.2';
   LIBNSS_NIS_SO = 'libnss_nis.so.2';
   LIBPTHREAD_SO = 'libpthread.so.0';
   LIBRESOLV_SO = 'libresolv.so.2';
   LIBRT_SO = 'librt.so.1';
   LIBTHREAD_DB_SO = 'libthread_db.so.1';
   LIBUTIL_SO = 'libutil.so.1';

