
const
  _PATH_DEFPATH = '/usr/bin:/bin';
  _PATH_STDPATH = '/usr/bin:/bin:/usr/sbin:/sbin';
  _PATH_BSHELL     = '/bin/sh';
  _PATH_CONSOLE = '/dev/console';
  _PATH_CSHELL = '/bin/csh';
  _PATH_DEVDB = '/var/run/dev.db';
  _PATH_DEVNULL = '/dev/null';
  _PATH_DRUM = '/dev/drum';
  _PATH_KLOG = '/proc/kmsg';
  _PATH_KMEM = '/dev/kmem';
  _PATH_LASTLOG = '/var/log/lastlog';
  _PATH_MAILDIR = '/var/mail';
  _PATH_MAN = '/usr/share/man';
  _PATH_MEM = '/dev/mem';
  _PATH_MNTTAB = '/etc/fstab';
  _PATH_MOUNTED = '/etc/mtab';
  _PATH_NOLOGIN = '/etc/nologin';
  _PATH_PRESERVE = '/var/lib';
  _PATH_RWHODIR = '/var/spool/rwho';
  _PATH_SENDMAIL = '/usr/sbin/sendmail';
  _PATH_SHADOW = '/etc/shadow';
  _PATH_SHELLS = '/etc/shells';
  _PATH_TTY = '/dev/tty';
  _PATH_UNIX = '/boot/vmlinux';
  _PATH_UTMP = '/var/run/utmp';
  _PATH_VI = '/usr/bin/vi';
  _PATH_WTMP = '/var/log/wtmp';
  _PATH_DEV = '/dev/';
  _PATH_TMP = '/tmp/';
  _PATH_VARDB = '/var/db/';
  _PATH_VARRUN = '/var/run/';
  _PATH_VARTMP = '/var/tmp/';

