
const
   EX_OK = 0;
   EX__BASE = 64;
   EX_USAGE = 64;
   EX_DATAERR = 65;
   EX_NOINPUT = 66;
   EX_NOUSER = 67;
   EX_NOHOST = 68;
   EX_UNAVAILABLE = 69;
   EX_SOFTWARE = 70;
   EX_OSERR = 71;
   EX_OSFILE = 72;
   EX_CANTCREAT = 73;
   EX_IOERR = 74;
   EX_TEMPFAIL = 75;
   EX_PROTOCOL = 76;
   EX_NOPERM = 77;
   EX_CONFIG = 78;
   EX__MAX = 78;


{ ---------------------------------------------------------------------
    Borland compatibility types
  ---------------------------------------------------------------------}

// Type
