//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclThreadNameExpert-D.xml)
            
     Last generated: 16-10-2005  03:42:06 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("JclThreadNameExpertC50.res");
USEUNIT("..\..\experts\debug\JclOTAUtils.pas");
USEUNIT("..\..\experts\debug\threadnames\ThreadExpertUnit.pas");
USEUNIT("..\..\experts\debug\threadnames\ThreadExpertSharedNames.pas");
USEPACKAGE("vcl50.bpi");
USEPACKAGE("dsnide50.bpi");
USEPACKAGE("JclC50.bpi");

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

