//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (%XMLNAME%)
            
     Last generated: %DATETIME%     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#pragma hdrstop
USERES("%NAME%.res");
<%%% START FILES %%%>
USEUNIT("%FILENAME%");
<%%% END FILES %%%>
<%%% START REQUIRES %%%>
USEPACKAGE("%NAME%.bpi");
<%%% END REQUIRES %%%>

//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------

//   Package source.
//---------------------------------------------------------------------------

#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

