{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (Jcl-R.xml)

     Last generated: 07-05-2010  18:46:59 UTC
-----------------------------------------------------------------------------
}

unit Jcl; 

interface

uses
  bzip2,
  Jcl8087,
  JclAnsiStrings,
  JclBase,
  JclCharsets,
  JclComplex,
  JclCompression,
  JclCounter,
  JclDateTime,
  JclExprEval,
  JclFileUtils,
  JclIniFiles,
  JclLogic,
  JclMath,
  JclMIDI,
  JclMime,
  JclNotify,
  JclPCRE,
  JclResources,
  JclRTTI,
  JclSchedule,
  JclSimpleXml,
  JclStatistics,
  JclStreams,
  JclStrHashMap,
  JclStringConversions,
  JclStringLists,
  JclStrings,
  JclSynch,
  JclSysInfo,
  JclSysUtils,
  JclUnicode,
  JclUnitConv,
  JclUnitVersioning,
  JclUnitVersioningProviders,
  JclValidation,
  JclWideStrings,
  pcre,
  zlibh,
  Hardlinks,
  JclAppInst,
  JclCIL,
  JclCLR,
  JclCOM,
  JclConsole,
  JclDebug,
  JclDebugSerialization,
  JclDebugXMLDeserializer,
  JclDebugXMLSerializer,
  JclDotNet,
  JclHookExcept,
  JclLANMan,
  JclLocales,
  JclMetadata,
  JclMiscel,
  JclMsdosSys,
  JclMultimedia,
  JclNTFS,
  JclPeImage,
  JclRegistry,
  JclSecurity,
  JclShell,
  JclStructStorage,
  JclSvcCtrl,
  JclTask,
  JclTD32,
  JclTimeZones,
  JclWin32,
  JclWin32Ex,
  JclWinMIDI,
  mscoree_TLB,
  mscorlib_TLB,
  MSTask,
  sevenzip,
  Snmp
  ;

implementation

end.
