{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (Jcl-R.xml)

     Last generated: 10-08-2009  13:49:46 UTC
-----------------------------------------------------------------------------
}

unit Jcl; 

interface

uses
  bzip2,
  Jcl8087,
  JclAnsiStrings,
  JclBase,
  JclBorlandTools,
  JclCharsets,
  JclComplex,
  JclCompression,
  JclCounter,
  JclDateTime,
  JclEDI,
  JclEDISEF,
  JclEDITranslators,
  JclEDIXML,
  JclEDI_ANSIX12,
  JclEDI_ANSIX12_Ext,
  JclEDI_UNEDIFACT,
  JclEDI_UNEDIFACT_Ext,
  JclExprEval,
  JclFileUtils,
  JclIniFiles,
  JclLogic,
  JclMath,
  JclMIDI,
  JclMime,
  JclNotify,
  JclPCRE,
  JclResources,
  JclRTTI,
  JclSimpleXml,
  JclSchedule,
  JclStatistics,
  JclStreams,
  JclStrHashMap,
  JclStringConversions,
  JclStringLists,
  JclStrings,
  JclSynch,
  JclSysInfo,
  JclSysUtils,
  JclUnicode,
  JclUnitConv,
  JclUnitVersioning,
  JclUnitVersioningProviders,
  JclValidation,
  JclWideStrings,
  pcre,
  zlibh,
  Hardlinks,
  JclAppInst,
  JclCIL,
  JclCLR,
  JclCOM,
  JclConsole,
  JclDebug,
  JclDebugSerialization,
  JclDebugXMLDeserializer,
  JclDebugXMLSerializer,
  JclDotNet,
  JclHookExcept,
  JclLANMan,
  JclLocales,
  JclMetadata,
  JclMiscel,
  JclMsdosSys,
  JclMultimedia,
  JclNTFS,
  JclPeImage,
  JclRegistry,
  JclSecurity,
  JclShell,
  JclStructStorage,
  JclSvcCtrl,
  JclTask,
  JclTD32,
  JclWin32,
  JclWin32Ex,
  JclWinMIDI,
  mscoree_TLB,
  mscorlib_TLB,
  MSHelpServices_TLB,
  MSTask,
  sevenzip,
  Snmp
  ;

implementation

end.
