{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclContainers-R.xml)

     Last generated: 07-05-2010  18:24:22 UTC
-----------------------------------------------------------------------------
}

unit JclContainers; 

interface

uses
  JclAbstractContainers,
  JclAlgorithms,
  JclArrayLists,
  JclArraySets,
  JclBinaryTrees,
  JclContainerIntf,
  JclHashMaps,
  JclHashSets,
  JclLinkedLists,
  JclQueues,
  JclSortedMaps,
  JclStacks,
  JclTrees,
  JclVectors
  ;

implementation

end.
