{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclDeveloperTools-R.xml)

     Last generated: 07-05-2010  18:24:22 UTC
-----------------------------------------------------------------------------
}

unit JclDeveloperTools; 

interface

uses
  JppState,
  JppLexer,
  JppParser,
  JclCompilerUtils,
  JclDevToolsResources,
  JclIDEUtils,
  JclUsesUtils,
  JclHelpUtils,
  MSHelpServices_TLB
  ;

implementation

end.
