{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclDeveloperTools-R.xml)

     Last generated: 03-02-2010  19:54:54 UTC
-----------------------------------------------------------------------------
}

unit JclDeveloperTools; 

interface

uses
  JclCompilerUtils,
  JclDevToolsResources,
  JclIDEUtils,
  JclHelpUtils,
  MSHelpServices_TLB
  ;

implementation

end.
