{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclDeveloperTools-R.xml)

     Last generated: 29-07-2010  14:18:18 UTC
-----------------------------------------------------------------------------
}

unit JclDeveloperTools; 

interface

uses
  JppState,
  JppLexer,
  JppParser,
  JclTemplates,
  JclCompilerUtils,
  JclDevToolsResources,
  JclIDEUtils,
  JclUsesUtils,
  JclHelpUtils,
  MSHelpServices_TLB
  ;

implementation

end.
