Library JclStackTraceViewerExpertDLL;
{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclStackTraceViewerExpertDLL-L.xml)

     Last generated: 26-04-2009  23:50:24 UTC
-----------------------------------------------------------------------------
}

{$R *.res}
{$ALIGN 8}
{$ASSERTIONS ON}
{$BOOLEVAL OFF}
{$DEBUGINFO OFF}
{$EXTENDEDSYNTAX ON}
{$IMPORTEDDATA ON}
{$IOCHECKS ON}
{$LOCALSYMBOLS OFF}
{$LONGSTRINGS ON}
{$OPENSTRINGS ON}
{$OPTIMIZATION ON}
{$OVERFLOWCHECKS OFF}
{$RANGECHECKS OFF}
{$REFERENCEINFO OFF}
{$SAFEDIVIDE OFF}
{$STACKFRAMES OFF}
{$TYPEDADDRESS OFF}
{$VARSTRINGCHECKS ON}
{$WRITEABLECONST ON}
{$MINENUMSIZE 1}
{$IMAGEBASE $58120000}
{$DESCRIPTION 'JCL Stack Trace Viewer'}
{$LIBSUFFIX '120'}
{$IMPLICITBUILD OFF}

{$DEFINE BCB}
{$DEFINE RELEASE}

uses
  ToolsAPI,
  JclStackTraceViewerImpl in '..\..\experts\stackviewer\JclStackTraceViewerImpl.pas' ,
  JclStackTraceViewerExceptInfoFrame in '..\..\experts\stackviewer\JclStackTraceViewerExceptInfoFrame.pas' {frmException: TFrame},
  JclStackTraceViewerStackFrame in '..\..\experts\stackviewer\JclStackTraceViewerStackFrame.pas' {frmStack: TFrame},
  JclStackTraceViewerThreadFrame in '..\..\experts\stackviewer\JclStackTraceViewerThreadFrame.pas' {frmThread: TFrame},
  StackFrame2 in '..\..\experts\stackviewer\StackFrame2.pas' {frmStack2: TFrame},
  JclStackTraceViewerModuleFrame in '..\..\experts\stackviewer\JclStackTraceViewerModuleFrame.pas' {frmModule: TFrame},
  JclStackTraceViewerMainFormBDS in '..\..\experts\stackviewer\JclStackTraceViewerMainFormBDS.pas' {frmStackView},
  JclStackTraceViewerMainFrame in '..\..\experts\stackviewer\JclStackTraceViewerMainFrame.pas' {frmMain: TFrame},
  JclStackTraceViewerConfigFrame in '..\..\experts\stackviewer\JclStackTraceViewerConfigFrame.pas' {JclStackTraceViewerConfigFrame: TFrame},
  StackViewUnit in '..\..\experts\stackviewer\StackViewUnit.pas' ,
  StackCodeUtils in '..\..\experts\stackviewer\StackCodeUtils.pas' ,
  JclStackTraceViewerOptions in '..\..\experts\stackviewer\JclStackTraceViewerOptions.pas' ,
  JclStackTraceViewerAPIImpl in '..\..\experts\stackviewer\JclStackTraceViewerAPIImpl.pas' ,
  JclStackTraceViewerAPI in '..\..\experts\stackviewer\JclStackTraceViewerAPI.pas' ,
  FileSearcherUnit in '..\..\experts\stackviewer\FileSearcherUnit.pas' ,
  JclDebugSerialization in '..\..\experts\stackviewer\JclDebugSerialization.pas' ,
  JclDebugXMLDeserializer in '..\..\experts\stackviewer\JclDebugXMLDeserializer.pas' 
  ;

exports
  JCLWizardInit name WizardEntryPoint;

end.
